#!/usr/bin/python3

TILEMAP_PATH = "assets/tilemaps"
OUTPUT_PATH = "src/leveldata.ts"


import glob
import xml.etree.ElementTree as ET
import os


files = sorted(glob.glob(TILEMAP_PATH + "/*.tmx"))

def parse_tilemap(path):
    for d in ET.parse(path).getroot().iter("data"):
        return d.text.replace("\n", "")

data = []
for f in files:
    data.append(parse_tilemap(f))

f = open(OUTPUT_PATH, "w")

f.write("// Generated by mapconv.py\n")
f.write("export const LEVEL_DATA = [\n\t")
for d in data:
    f.write("\t[" + d + "],\n")

f.write("]\n")
f.close()
